language:
    python

python:
    - "2.7"

install:
    "pip install -r requirements.txt"

branches:
    only:
        - testing
        - master

script:
    - export PYTHONPATH=${PYTHONPATH}:$(pwd)
    - coverage run --branch --source oppy $(which trial) oppy
    - nosetests oppy/ --config=.noserc

after_success:
    - coveralls
